<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>التقرير المالي</title>@include('documents._styles')</head><body><main class="document">
@php($companyId=auth()->user()?->company_id)
@include('documents._header',['companyId'=>$companyId,'documentTitle'=>'التقرير المالي'])
<table class="hero"><tr><td><div class="hero-title">ملخص الأداء المالي</div><div class="hero-subtitle">القبض والصرف والحركة اليومية</div></td><td class="hero-meta">الفترة<strong>{{ $from?:'البداية' }} — {{ $to?:'اليوم' }}</strong></td></tr></table>
<table class="summary"><tr><td>الرصيد الحالي<span class="value">{{ number_format($balance,2) }}</span></td><td>إجمالي القبض<span class="value positive">{{ number_format($totalReceipts,2) }}</span></td><td>إجمالي الصرف<span class="value negative">{{ number_format($totalPayments,2) }}</span></td><td>صافي الحركة<span class="value">{{ number_format($totalReceipts-$totalPayments,2) }}</span></td></tr></table>
<h2 class="section-title">سندات القبض</h2><table class="data"><thead><tr><th>رقم السند</th><th>الطرف</th><th>التاريخ</th><th>المبلغ</th></tr></thead><tbody>@forelse($receipts as $item)<tr><td>{{ $item->receipt_no }}</td><td>{{ $item->party?->name??'-' }}</td><td>{{ $item->receipt_date }}</td><td class="positive">{{ number_format($item->amount,2) }}</td></tr>@empty<tr><td colspan="4">لا توجد بيانات</td></tr>@endforelse</tbody></table>
<h2 class="section-title">سندات الصرف</h2><table class="data"><thead><tr><th>رقم السند</th><th>الطرف</th><th>التاريخ</th><th>المبلغ</th></tr></thead><tbody>@forelse($payments as $item)<tr><td>{{ $item->payment_no }}</td><td>{{ $item->party?->name??'-' }}</td><td>{{ $item->payment_date }}</td><td class="negative">{{ number_format($item->amount,2) }}</td></tr>@empty<tr><td colspan="4">لا توجد بيانات</td></tr>@endforelse</tbody></table>
<h2 class="section-title">الحركة اليومية</h2><table class="data"><thead><tr><th>التاريخ</th><th>الداخل</th><th>الخارج</th><th>الصافي</th></tr></thead><tbody>@forelse($cashMovement as $row)<tr><td>{{ $row['date'] }}</td><td class="positive">{{ number_format($row['in'],2) }}</td><td class="negative">{{ number_format($row['out'],2) }}</td><td>{{ number_format($row['net'],2) }}</td></tr>@empty<tr><td colspan="4">لا توجد بيانات</td></tr>@endforelse</tbody></table>
@include('documents._footer')</main>@unless($pdfMode??false)<div class="actions"><button onclick="window.print()">طباعة / حفظ PDF</button></div>@endunless</body></html>
